def q():
    questList = [["You have some free time. What do you do?",[['1. Explore the Capital', 2,3,5],
                                                              ["2. Party like I'm gonna die tomorrow", -2,-1,13],
                                                              ['3. Work out', 8,1,1],
                                                              ['4. Sleep', 4,4,2]]],
                 ["The training room is at your disposal. What do you do?",[["1. Silently meditate", 0,10,0],
                                                                            ["2. Pick a fight with another participant", 8,2,-2],
                                                                            ['3. Sleep', 4,4,2],
                                                                            ["4. Train with some of the equipment", 4,0,0]]],
                 ["Your advisor tells you to start practicing with a weapon. What weapon do you choose?", [["1. Forget that, I don't need a weapon", -1,-1,12],
                                                                                                           ["2. I train in something I don't normally use", 4,4,2],
                                                                                                           ["3. I grab a weapon I am familiar with", 6,6,-2],
                                                                                                           ["4. I experiment with different weapons and find what feels best", 2,2,6]]],
                 ["A scuffle breaks out in the training room while you're there. What do you do?", [["1. Hide in a corner", -2,2,10],
                                                                                                    ["2. Jump in the fray", 10,0,0],
                                                                                                    ["3. Shout to diffuse the situation", 0,8,2],
                                                                                                    ["4. Sit and watch", 2,4,4]]],
                 ["Another contestant tries to start a fight with you. What do you do?",[['1. Avoid conflict and walk away', 3,4,3],
                                                                                         ['2. I never back down from a fight!', 7,-1,4],
                                                                                         ['3. Ignore them for as long as possible', 2,4,4],
                                                                                         ["4. Expertly diffuse the situation while simultaneously humiliating the aggressor", 0,8,2]]],
                 ["The weapons rack is open for the moment. What do you choose?",[["1. I don't think I'll need a weapon", -1,-1,12],
                                                                                  ['2. Something light, but fast', 3,4,3],
                                                                                  ['3. I pick up the whole rack and throw it at something/someone!', 13,-3,0],
                                                                                  ["4. I like a versatile weapon with a lot of uses", 3,8,-1]]],
                 ["It's now time to develop a battle plan for the arena. What's your strategy?",[['1. Head straight for the cornicopia and never look back', 10,0,0],
                                                                                                 ['2. Run the exact opposite direction of the cornicopia', 0,0,10],
                                                                                                 ['3. Take in my suroundings and make it up as I go', 3,4,3],
                                                                                                 ["4. Try to form an alliance with the other tributes", 0,10,0]]],
                 ["What is your favorite color?",[['1. red or yellow', 3,3,4],
                                                  ['2. blue or purple', 4,3,3],
                                                  ['3. green or orange', 3,4,3],
                                                  ['4. black or white', 4,4,2]]],
                 ["Do you like Cracker Barrel Buttered Biscuits?",[['1. yes.', 3,3,4],
                                                  ['2. definitely!', 4,3,3],
                                                  ['3. absolutely!!', 3,4,3],
                                                  ['4. I think this question is rigged', 4,4,2]]],
                 ["You find yourself in front of a computer with a list of survival skills. Which one do you choose to learn?",[['1. I learn how to make traps', 3,5,2],
                                                  ['2. I learn how to camouflage myself', 2,4,4],
                                                  ['3. I learn how to perform first aid', 6,2,2],
                                                  ['4. I learn about what is edible and what is not in different environments', 3,3,4]]],
                 ["Once you get there, what do you hate most about the Capital?",[['1. Nothing, it seems like a fun place', 5,3,2],
                                                  ['2. I hate the fact that everyone here is waiting for me to die', 2,6,2],
                                                  ['3. I hate their powdered faces, fluffy clothes, and ridiculous hair', 4,4,2],
                                                  ['4. Everything. I hate everything', 4,3,3]]],
                 ["One of the players looks depressed and is keeping to themselves. What do you do?",[['1. Nothing. Who cares?', 3,3,4],
                                                  ["2. Nothing. He's probably going to die and nothing I say is going to change that", 4,3,3],
                                                  ['3. I attempt to comfort and/or encourage him', 3,4,3],
                                                  ['4. I make it much much worse >:)', 4,4,2]]]
                 ]
    return questList
